### ISSUE TITLE
skale node register transaction fails

### ISSUE THREAD

**Issue by nate-staked** [skalenetwork/node-cli#290]
This issue might be better off filed in the [skale-manager](https://github.com/skalenetwork/skale-manager) repo but I'm filing it here because I encountered it while using the `skale` cli tool.

## background
I am setting up a 2nd node for my validator.

### config:
```
SGX_SERVER_URL=https://<redacted>:1026/

# use your 200gb external storage mount point
# this was manually created and attached using azure web gui
DISK_MOUNTPOINT=/dev/sdc

# This will be used for later testing.
# It’s for interchain messaging agent feature for dApp developers.
# For now you don’t have to worry about this part. We will provide more information later on.
IMA_CONTRACTS_ABI_URL=https://skale-contracts.nyc3.digitaloceanspaces.com/beta/ima.json

# This manager contracts abi url is where the SKALE manager smart contract ABI lives.
# This can change based on the beta versions or develop versions...
# see: https://forum.skale.network/t/examples-environment-variables-hard-upgrade/197
MANAGER_CONTRACTS_ABI_URL=https://skale-contracts.nyc3.digitaloceanspaces.com/fuji-testnet/manager.json

# "This is for elastic search and for skale to monitor during testnet.
# It will be retired for the mainnet.
# It would be very cool if you can add this variable for now."
FILEBEAT_HOST=3.17.12.121:5000

CONTAINER_CONFIGS_STREAM=alpine-hard-upgrade
DOCKER_LVMPY_STREAM=beta
DB_PORT=3306
DB_ROOT_PASSWORD=test
DB_PASSWORD=test
DB_USER=test
IMA_ENDPOINT=rinkeby.infura.io/v3/<redacted>
ENDPOINT=https://rinkeby.infura.io/v3/<redacted>
NODE_CLI_SPACE=develop
SKALE_NODE_CLI_VERSION=0.10.0-develop.2

# see also: https://forum.skale.network/t/example-environment-variables/106


# Variables added during hard upgrade:

# True/False will enable monitoring containers (filebeat, cadvisor, prometheus)
# Required for TestNets
MONITORING_CONTAINERS=True
```

### steps:
```
# initialize skale node
skale node init --install-deps ./env

# initialize skale validator
sk-val init \
  -e wss://rinkeby.infura.io/ws/v3/<redacted> \
  -c https://skale-contracts.nyc3.digitaloceanspaces.com/fuji-testnet/manager.json \
  --wallet software

# get your skale validator signature
export VALIDATOR_NAME=staked
export VALIDATOR_ID="$(sk-val validator ls | grep $VALIDATOR_NAME | awk '{ print $2 }')"
export SIGNATURE="$(skale node signature $VALIDATOR_ID | cut -d' ' -f2)"

# link your validator address to your node address
# (NOTE: assumes you have the validator private key saved to validator-pk.txt)

export NODE_ADDRESS="$(skale wallet info | grep Address | cut -d' ' -f2)"
sk-val validator link-address $NODE_ADDRESS $SIGNATURE --yes --pk-file ./validator-pk.txt
# ✔ Node address 0x9e6737c6C3B... linked to your validator address

export NODE_NAME='skale-node-vm'   # new node name
export IP_ADDRESS="$(curl ifconfig.co)"
export PORT_RANGE_START='10000'

skale node register --name $NODE_NAME --ip $IP_ADDRESS --port $PORT_RANGE_START
```

## tx failure
The [link-address transaction](https://rinkeby.etherscan.io/tx/0x17c74bd1e6712c34bef760a29e00f6dcd1524c5afb8eb469485be06ab69f03b2) from my validator succeeds, but the [register-node transaction](https://rinkeby.etherscan.io/tx/0xf6d5a00065681a0b0f1bf5fe8068e881db2fd589d2ecfbcfc5014038a929bbbf) from my node fails.

### logs
Here are the logs from my skale_api container:
```
[2020-08-26 01:15:37 +0000] [8] [DEBUG] POST /create-node
[2020-08-26 01:16:08,096 INFO] core.node - MainThread -
====================================================================================================
Node create started
IP: 52.249.250.53
Public IP: 52.249.250.53
Port: 10000
Name: skale-node-secret-vm
====================================================================================================

[2020-08-26 01:16:08,336 INFO] skale.contracts.manager - MainThread - create_node: 52.249.250.53:10000, public ip: 52.249.250.53 name: skale-node-secret-vm
[2020-08-26 01:16:08,342 INFO] skale.transactions.tools - MainThread - Dry run tx: createNode, sender: 0x9e6737c6C3B69397c439d1D2084D8d1dDB8669C9, wallet: RPCWallet, gasLimit: 3500000
[2020-08-26 01:16:08,383 INFO] skale.transactions.tools - MainThread - Tx: createNode, sender: 0x9e6737c6C3B69397c439d1D2084D8d1dDB8669C9, wallet: RPCWallet, gasLimit: 3500000, gasPrice: 1250000000
[2020-08-26 01:16:51,156 INFO] skale.utils.web3_utils - MainThread - Current block number is 7083252, waiting for 5 confimration blocks to be mined
[2020-08-26 01:18:26,742 ERROR] core.node - MainThread - Node creation failed
Traceback (most recent call last):
  File "/usr/src/admin/core/node.py", line 91, in register
    confirmation_blocks=NODE_REGISTER_CONFIRMATION_BLOCKS
  File "/usr/local/lib/python3.7/dist-packages/skale/contracts/base_contract.py", line 84, in wrapper
    tx_res.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/skale/transactions/result.py", line 98, in raise_for_status
    raise TransactionFailedError(f'Transaction failed. '
skale.transactions.result.TransactionFailedError: Transaction failed. See receipt AttributeDict({'blockHash': HexBytes('0x712fd83da4980afc80cc99fe4426db13f73c2b8540dc3e885edcf284ced62507'), 'blockNumber': 7083252, 'contractAddress': None, 'cumulativeGasUsed': 7291385, 'from': '0x9e6737c6C3B69397c439d1D2084D8d1dDB8669C9', 'gasUsed': 3359503, 'logs': [], 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'to': '0x139360fc743b1DA2adb43F5999E28998Da3b6285', 'transactionHash': HexBytes('0xf6d5a00065681a0b0f1bf5fe8068e881db2fd589d2ecfbcfc5014038a929bbbf'), 'transactionIndex': 1})
```

**Comment by nate-staked** [comment]
I tried upgrading to a version `0.10.1-beta.1` at Ebru's direction:
```
export NODE_VERSION_NUM=0.10.1-beta.1
sudo -E bash -c "curl -L https://skale-cli.sfo2.cdn.digitaloceanspaces.com/beta/skale-${NODE_VERSION_NUM}-`uname -s`-`uname -m` >  /usr/local/bin/skale-${NODE_VERSION_NUM}"
sudo chmod +x /usr/local/bin/skale-${NODE_VERSION_NUM}
ln -fs /usr/local/bin/skale-${NODE_VERSION_NUM} /usr/local/bin/skale

skale node update ./env
```

but still got the same error: https://rinkeby.etherscan.io/tx/0x1eef3ce1ad0f1bbe96c2317f88916652a082c622caccffd166834a0ae1f4e658

skale_api logs:
```
[2020-08-26 20:34:51 +0000] [8] [DEBUG] POST /create-node
[2020-08-26 20:35:21,840 INFO] core.node - MainThread -
====================================================================================================
Node create started
IP: 52.249.250.53
Public IP: 52.249.250.53
Port: 10000
Name: skale-1
====================================================================================================

[2020-08-26 20:35:21,939 INFO] skale.contracts.manager - MainThread - create_node: 52.249.250.53:10000, public ip: 52.249.250.53 name: skale-1
[2020-08-26 20:35:21,946 INFO] skale.transactions.tools - MainThread - Dry run tx: createNode, sender: 0x9e6737c6C3B69397c439d1D2084D8d1dDB8669C9, wallet: RPCWallet, gasLimit: 3500000
[2020-08-26 20:35:21,980 INFO] skale.transactions.tools - MainThread - Tx: createNode, sender: 0x9e6737c6C3B69397c439d1D2084D8d1dDB8669C9, wallet: RPCWallet, gasLimit: 3500000, gasPrice: 1250000000
[2020-08-26 20:36:08,837 INFO] skale.utils.web3_utils - MainThread - Current block number is 7087888, waiting for 5 confimration blocks to be mined
[2020-08-26 20:37:34,282 ERROR] core.node - MainThread - Node creation failed
Traceback (most recent call last):
  File "/usr/src/admin/core/node.py", line 91, in register
    confirmation_blocks=NODE_REGISTER_CONFIRMATION_BLOCKS
  File "/usr/local/lib/python3.7/dist-packages/skale/contracts/base_contract.py", line 84, in wrapper
    tx_res.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/skale/transactions/result.py", line 98, in raise_for_status
    raise TransactionFailedError(f'Transaction failed. '
skale.transactions.result.TransactionFailedError: Transaction failed. See receipt AttributeDict({'blockHash': HexBytes('0x71f4ca90f8f4f9faca550decf373bbf2206681a6e605925e4d9c556672fd307d'), 'blockNumber': 7087889, 'contractAddress': None, 'cumulativeGasUsed': 3814470, 'from': '0x9e6737c6C3B69397c439d1D2084D8d1dDB8669C9', 'gasUsed': 3359496, 'logs': [], 'logsBloom': HexBytes('0x00
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), 'status': 0, 'to': '0x139360fc743b1DA2adb43F5999E28998Da3b6285', 'transactionHash': HexBytes('0x1eef3ce1ad0f1bbe96c2317f88916652a082c622caccffd166834a0ae1f4e658'), 'transactionIndex': 3})
```

**Comment by dmytrotkk** [comment]
Hey @nate-staked ✋ 
Thank you for such detailed logs and explanations.

It looks like node register transaction took more gas than it was originally expected (3.5m) so it ran out of gas. We'll create a hotfix for this particular transaction ASAP. We'll ping you when the release of skale-node will be shipped so you can update. 

Also, we have a ticket about the new approach of gas estimation in the skale.py library - it will be implemented in the nearest future.

**Comment by dmytrotkk** [comment]
@nate-staked 👋

We pushed a hotfix for this issue to the `alpine-hard-upgrade` branch in the `skale-node`.
Now you can update your software and try to register again:

1) Re-check your `.env` file - `CONTAINER_CONFIGS_STREAM` should be equal to `alpine-hard-upgrade`
2) Run `skale node update --yes [PATH-TO-ENV-FILE]`
3) Register a node: `skale node register`

Feel free to close the issue if you will be able to register a node after this fix.

**Comment by nate-staked** [comment]
that worked 🎉 

https://rinkeby.etherscan.io/tx/0x0e28a8c10f7efba3a36767f37f84e010dadc8678e7bc1e720ae7adda6cb274c1

thanks!
