### ISSUE TITLE
skale ssl upload returns exit code 0 on failure

### ISSUE THREAD

**Issue by JonasPf** [skalenetwork/node-cli#438]
When I run `skale ssl upload` and it fails due to permission problems I'd expect to get a non-zero exit code. This would make automation far easier because I wouldn't need to parse the output to determine if the command was successful.

```
$ skale ssl upload -c fullchain.pem -k privkey.pem
Command execution failed with [Errno 13] Permission denied: 'privkey.pem'. Recheck your inputs
Traceback (most recent call last):
  File "main.py", line 111, in <module>
  File "site-packages/click/core.py", line 829, in __call__
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "cli/ssl.py", line 71, in upload
  File "core/helper.py", line 188, in upload_certs
PermissionError: [Errno 13] Permission denied: 'privkey.pem'
2021-03-09 17:00:22,278 - [Errno 13] Permission denied: 'privkey.pem'
```

Followed by:

```
$ echo $?
0
```

Would be great if this could return something other than `0`.

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3976)

**Comment by dmytrotkk** [comment]
Hey, @JonasPf!

We're aware of the exit-codes issue and even addressed it in https://github.com/skalenetwork/node-cli/pull/388.
Unfourtenantly, this enhancement wasn't included in the current Testnet release and now present only in the `develop` branch. 

Here are the exit codes that will be used in the next release of node-cli: https://github.com/skalenetwork/node-cli#exit-codes

**Comment by gannakulikova** [comment]
Hi @JonasPf !
I'm closing this issue for now as it has been addressed, please feel free to re-open if there are any questions left.
Thank you and have a great day!
