### ISSUE TITLE
Failing skale node-sync command (cannot find docker/lvmpy.json)

### ISSUE THREAD

**Issue by david-bartos** [skalenetwork/node-cli#724]
**Describe the bug**
During sync node initialization (trying to run Chaos testnet), the process is failing while running ~/.skale/docker-lvmpy/scripts/install.sh

**To Reproduce**
install plain VM (I had been using Google cloud instance of Ubuntu 22.04)
configure prerequisities - swap, packages, docker, docker compose
Then run (root user)
```
VERSION_NUM=2.2.0-sync-node.6 && sudo -E bash -c "curl -L https://github.com/skalenetwork/node-cli/releases/download/$VERSION_NUM/skale-$VERSION_NUM-`uname -s`-`uname -m`-sync >  /usr/local/bin/skale"
chmod +x /usr/local/bin/skale
skale node-init ./env
```
My env file content:
```
# env
CONTAINER_CONFIGS_STREAM="2.2.0-sync-node.0"
ENDPOINT="https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix"
MANAGER_CONTRACTS_ABI_URL="https://raw.githubusercontent.com/skalenetwork/skale-network/master/releases/mainnet/skale-manager/1.9.0/skale-manager-1.9.0-mainnet-abi.json"
IMA_CONTRACTS_ABI_URL="https://raw.githubusercontent.com/skalenetwork/skale-network/master/releases/mainnet/IMA/1.3.0/mainnet/abi.json"
DISK_MOUNTPOINT=/data
DOCKER_LVMPY_STREAM="master"
ENV_TYPE="testnet"
SCHAIN_NAME="staging-fast-active-bellatrix"
```

It will progress but eventually fail with:
```
root@david-instance:~/.skale# skale sync-node init ../env
Configuring firewall ...
2023-04-27 12:13:59,207 - INFO - Configuring iptables...
Done
2023-04-27 12:13:59,274 - INFO - /root/.skale/.tmp/config doesn't exist, skipping...
2023-04-27 12:13:59,274 - INFO - Creating /root/.skale/.tmp/config directory...
2023-04-27 12:13:59,275 - INFO - Cloning https://github.com/skalenetwork/skale-node.git → /root/.skale/.tmp/config
2023-04-27 12:14:00,159 - INFO - Fetching config changes
2023-04-27 12:14:00,559 - INFO - Checkouting /root/.skale/.tmp/config to 2.2.0-sync-node.0
2023-04-27 12:14:00,580 - INFO - Configuring docker
2023-04-27 12:14:00,581 - INFO - Ensuring docker service dir
2023-04-27 12:14:00,581 - INFO - Ensuring docker service override config
2023-04-27 12:14:00,581 - INFO - Ensuring docker daemon config
2023-04-27 12:14:00,582 - INFO - Updating docker daemon config
2023-04-27 12:14:00,582 - INFO - Docker config changes [<DockerConfigResult.UNCHANGED: 0>, <DockerConfigResult.UNCHANGED: 0>, <DockerConfigResult.UNCHANGED: 0>, <DockerConfigResult.CHANGED: 1>]
2023-04-27 12:14:00,582 - INFO - Executing daemon-reload
2023-04-27 12:14:00,884 - INFO - Restarting docker service
2023-04-27 12:14:01,942 - INFO - Waiting for docker inititalization
2023-04-27 12:14:01,942 - INFO - Socket initialized successfully
2023-04-27 12:14:01,942 - INFO - Docker configuration finished
2023-04-27 12:14:01,942 - INFO - Preparing host started
2023-04-27 12:14:01,943 - INFO - Creating symlink /root/.skale/.env → /root/.skale/config/.env
2023-04-27 12:14:01,996 - INFO - Processing nginx template. ssl: False
2023-04-27 12:14:02,001 - INFO - Sync repo https://github.com/skalenetwork/docker-lvmpy.git → /root/.skale/docker-lvmpy
2023-04-27 12:14:02,001 - INFO - Cloning https://github.com/skalenetwork/docker-lvmpy.git → /root/.skale/docker-lvmpy
2023-04-27 12:14:03,000 - INFO - Fetching docker-lvmpy changes
2023-04-27 12:14:03,440 - INFO - Checkouting /root/.skale/docker-lvmpy to master
2023-04-27 12:14:06,958 - ERROR - Error during shell execution:
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 https://download.docker.com/linux/ubuntu jammy InRelease
Hit:2 http://europe-west3.gce.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://europe-west3.gce.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://europe-west3.gce.archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
Building dependency tree...
Reading state information...
7 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
python3-dev is already the newest version (3.10.6-1~22.04).
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.2).
The following package was automatically installed and is no longer required:
  libnuma1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
cp: cannot stat 'docker/lvmpy.json': No such file or directory

Command execution failed with Command '['sudo', '-H', '-E', '/root/.skale/docker-lvmpy/scripts/install.sh']' returned non-zero exit status 1.. Recheck your inputs
Traceback (most recent call last):
  File "node_cli/main.py", line 116, in <module>
  File "site-packages/click/core.py", line 829, in __call__
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "node_cli/utils/helper.py", line 306, in wrapper
  File "node_cli/cli/sync_node.py", line 43, in _init_sync
  File "node_cli/utils/decorators.py", line 37, in inner
  File "node_cli/core/node.py", line 148, in init_sync
  File "node_cli/operations/base.py", line 169, in init_sync
  File "node_cli/operations/docker_lvmpy.py", line 74, in docker_lvmpy_install
  File "node_cli/utils/helper.py", line 112, in run_cmd
  File "subprocess.py", line 444, in check_returncode
subprocess.CalledProcessError: Command '['sudo', '-H', '-E', '/root/.skale/docker-lvmpy/scripts/install.sh']' returned non-zero exit status 1.
2023-04-27 12:14:06,960 - ERROR - Command failed with Command '['sudo', '-H', '-E', '/root/.skale/docker-lvmpy/scripts/install.sh']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "node_cli/main.py", line 116, in <module>
  File "site-packages/click/core.py", line 829, in __call__
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "node_cli/utils/helper.py", line 306, in wrapper
  File "node_cli/cli/sync_node.py", line 43, in _init_sync
  File "node_cli/utils/decorators.py", line 37, in inner
  File "node_cli/core/node.py", line 148, in init_sync
  File "node_cli/operations/base.py", line 169, in init_sync
  File "node_cli/operations/docker_lvmpy.py", line 74, in docker_lvmpy_install
  File "node_cli/utils/helper.py", line 112, in run_cmd
  File "subprocess.py", line 444, in check_returncode
subprocess.CalledProcessError: Command '['sudo', '-H', '-E', '/root/.skale/docker-lvmpy/scripts/install.sh']' returned non-zero exit status 1.
```

**Expected behavior**
I would expect the script to find the file 'docker/lvmpy.json' as it does exist and continue with whatever it should do next...

**Comment by badrogger** [comment]
@junkett Thank you for reporting the issue. Please try [2.2.1-beta-sync-node.3](https://github.com/skalenetwork/node-cli/releases/tag/2.2.1-beta-sync-node.3) with `DOCKER_LVMPY_STREAM=1.0.2-stable.0`

**Comment by david-bartos** [comment]
Hi @badrogger and thanks for suggestion - I had used specified versions but now getting into another issue:
Command I use to get node cli:
```
VERSION_NUM=2.2.1-beta-sync-node.3 && sudo -E bash -c "curl -L https://github.com/skalenetwork/node-cli/releases/download/$VERSION_NUM/skale-$VERSION_NUM-`uname -s`-`uname -m`-sync >  /usr/local/bin/skale" && sudo chmod +x /usr/local/bin/skale
```
My env now:
```
# env
CONTAINER_CONFIGS_STREAM="2.2.0-sync-node.0"
ENDPOINT="https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix"
MANAGER_CONTRACTS_ABI_URL="https://raw.githubusercontent.com/skalenetwork/skale-network/master/releases/mainnet/skale-manager/1.9.0/skale-manager-1.9.0-mainnet-abi.json"
IMA_CONTRACTS_ABI_URL="https://raw.githubusercontent.com/skalenetwork/skale-network/master/releases/mainnet/IMA/1.3.0/mainnet/abi.json"
DISK_MOUNTPOINT=/dev/sdb
DOCKER_LVMPY_STREAM="1.0.2-stable.0"
ENV_TYPE="testnet"
SCHAIN_NAME="staging-fast-active-bellatrix"
ENFORCE_BTRFS=True
```
I had to add `ENFORCE_BTRFS=True` to get past error I was getting without it
`ERROR - Command failed with 'ENFORCE_BTRFS'`
Which lead to script eventually creating and mounting my partition...
But right after that it fails with it cannot find the `/root/.skale/config/static_params.yaml `file, as it does not exist on expected path.
Logs:
```
root@david-instance:~# skale sync-node init env
Configuring firewall ...
2023-04-28 07:17:22,457 - INFO - Configuring iptables...
2023-04-28 07:17:22,478 - INFO - Configuring ssh port
2023-04-28 07:17:22,483 - INFO - Configuring incoming tcp ports
2023-04-28 07:17:22,507 - INFO - Configuring incoming udp ports
Done
2023-04-28 07:17:22,525 - INFO - Making sure /dev/sdb is not mounted
2023-04-28 07:17:22,525 - INFO - Removing all links from filestorage mapping
2023-04-28 07:17:22,526 - INFO - /root/.skale/.tmp/config doesn't exist, skipping...
2023-04-28 07:17:22,526 - INFO - Creating /root/.skale/.tmp/config directory...
2023-04-28 07:17:22,526 - INFO - Cloning https://github.com/skalenetwork/skale-node.git → /root/.skale/.tmp/config
2023-04-28 07:17:23,170 - INFO - Fetching config changes
2023-04-28 07:17:23,531 - INFO - Checkouting /root/.skale/.tmp/config to 2.2.0-sync-node.0
2023-04-28 07:17:23,553 - INFO - Configuring docker
2023-04-28 07:17:23,553 - INFO - Ensuring docker service dir
2023-04-28 07:17:23,553 - INFO - Ensuring docker service override config
2023-04-28 07:17:23,553 - INFO - Ensuring docker daemon config
2023-04-28 07:17:23,554 - INFO - Updating docker daemon config
2023-04-28 07:17:23,554 - INFO - Docker config changes [<DockerConfigResult.UNCHANGED: 0>, <DockerConfigResult.UNCHANGED: 0>, <DockerConfigResult.UNCHANGED: 0>, <DockerConfigResult.CHANGED: 1>]
2023-04-28 07:17:23,555 - INFO - Executing daemon-reload
2023-04-28 07:17:23,862 - INFO - Restarting docker service
2023-04-28 07:17:24,845 - INFO - Waiting for docker inititalization
2023-04-28 07:17:24,845 - INFO - Socket initialized successfully
2023-04-28 07:17:24,846 - INFO - Docker configuration finished
2023-04-28 07:17:24,846 - INFO - Preparing host started
2023-04-28 07:17:24,849 - INFO - Creating symlink /root/.skale/.env → /root/.skale/config/.env
2023-04-28 07:17:24,878 - INFO - Processing nginx template. ssl: False
2023-04-28 07:17:24,895 - ERROR - Error during shell execution:
2023-04-28 07:17:24,896 - INFO - Cannot get filesystem type Command '['blkid', '-o', 'udev', '/dev/sdb']' returned non-zero exit status 2.
2023-04-28 07:17:24,897 - INFO - /dev/sdb contains None filesystem
2023-04-28 07:17:24,897 - INFO - Formating /dev/sdb as btrfs
2023-04-28 07:17:26,385 - INFO - Mounting /dev/sdb device
Command execution failed with [Errno 2] No such file or directory: '/root/.skale/config/static_params.yaml'. Recheck your inputs
Traceback (most recent call last):
  File "node_cli/main.py", line 117, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "node_cli/utils/helper.py", line 319, in wrapper
  File "node_cli/cli/sync_node.py", line 70, in _init_sync
  File "node_cli/utils/decorators.py", line 37, in inner
  File "node_cli/core/node.py", line 161, in init_sync
  File "node_cli/operations/base.py", line 220, in init_sync
  File "node_cli/core/resources.py", line 120, in update_resource_allocation
  File "node_cli/core/resources.py", line 74, in compose_resource_allocation_config
  File "node_cli/utils/helper.py", line 196, in safe_load_yml
FileNotFoundError: [Errno 2] No such file or directory: '/root/.skale/config/static_params.yaml'
2023-04-28 07:17:26,403 - ERROR - Command failed with [Errno 2] No such file or directory: '/root/.skale/config/static_params.yaml'
Traceback (most recent call last):
  File "node_cli/main.py", line 117, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "node_cli/utils/helper.py", line 319, in wrapper
  File "node_cli/cli/sync_node.py", line 70, in _init_sync
  File "node_cli/utils/decorators.py", line 37, in inner
  File "node_cli/core/node.py", line 161, in init_sync
  File "node_cli/operations/base.py", line 220, in init_sync
  File "node_cli/core/resources.py", line 120, in update_resource_allocation
  File "node_cli/core/resources.py", line 74, in compose_resource_allocation_config
  File "node_cli/utils/helper.py", line 196, in safe_load_yml
FileNotFoundError: [Errno 2] No such file or directory: '/root/.skale/config/static_params.yaml'
root@david-instance:~# cat /root/.skale/config/static_params.yaml
cat: /root/.skale/config/static_params.yaml: No such file or directory
```

**Comment by badrogger** [comment]
@junkett Please
1. Run `rm -r .skale` 
2. set CONTAINER_CONFIG_STREAM to [2.1.15-sync-2.0](https://github.com/skalenetwork/skale-node/releases/tag/2.1.15-sync-2.0)
3. Retry the init procedure.

**Comment by david-bartos** [comment]
Hello @badrogger - thanks again for quick help, according to the logs the node initiation had completed - however I suppose the sync process is still not happening. I can see the containers are running but the logs are showing that there is a crash loop with following sequence repeating indefinitely:
```
[2023-05-02 07:03:20,549 INFO] - web.models.schain:191 - Creating schainrecord table...
[2023-05-02 07:03:20,549 INFO] - root:44 - Running migrations ...
[2023-05-02 07:03:20,550 INFO] - root:141 - Add column: SChainRecord.new_schain
[2023-05-02 07:03:20,550 INFO] - root:141 - Add column: SChainRecord.repair_mode
[2023-05-02 07:03:20,550 INFO] - root:141 - Add column: SChainRecord.needs_reload
[2023-05-02 07:03:20,551 INFO] - root:141 - Add column: SChainRecord.monitor_last_seen
[2023-05-02 07:03:20,551 INFO] - root:141 - Add column: SChainRecord.monitor_id
[2023-05-02 07:03:20,551 INFO] - root:141 - Add column: SChainRecord.config_version
[2023-05-02 07:03:20,552 INFO] - root:141 - Add column: SChainRecord.restart_count
[2023-05-02 07:03:20,552 INFO] - root:141 - Add column: SChainRecord.failed_rpc_count
[2023-05-02 07:03:20,553 INFO] - root:141 - Add column: SChainRecord.ssl_change_date
[2023-05-02 07:03:20,553 INFO] - root:141 - Add column: SChainRecord.snapshot_from
[2023-05-02 07:03:20,553 INFO] - core.ima.schain:40 - Going to generate a new ABI file for sChain IMA (/skale_vol/contracts_info/schain_ima_abi.json)
[2023-05-02 07:03:20,574 INFO] - core.ima.schain:43 - New ABI file for sChain IMA saved: /skale_vol/contracts_info/schain_ima_abi.json
[2023-05-02 07:03:20,574 INFO] - skale.skale_base:45 - Initing skale.py, endpoint: https://[ETH_IP]/v1/staging-fast-active-bellatrix, wallet: [SGX_IP]Type
[2023-05-02 07:03:20,593 INFO] - skale.skale_base:45 - Initing skale.py, endpoint: https://[ETH_IP]/v1/staging-fast-active-bellatrix, wallet: [SGX_IP]Type
[2023-05-02 07:03:21,643 ERROR] - __main__:82 - Sync node worker failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 1537, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/usr/local/lib/python3.8/site-packages/eth_abi/codec.py", line 196, in decode_abi
    return self.decode(types, data)
  File "/usr/local/lib/python3.8/site-packages/eth_abi/codec.py", line 210, in decode
    return decoder(stream)
  File "/usr/local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/usr/local/lib/python3.8/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/usr/local/lib/python3.8/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/usr/local/lib/python3.8/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sync_node.py", line 80, in main
    worker(SCHAIN_NAME)
  File "sync_node.py", line 51, in worker
    if not skale.schains_internal.is_schain_exist(schain_name):
  File "/usr/local/lib/python3.8/site-packages/skale/skale_base.py", line 126, in __getattr__
    self.__init_contract_from_info(abi, contract_info)
  File "/usr/local/lib/python3.8/site-packages/skale/skale_base.py", line 90, in __init_contract_from_info
    self.init_upgradeable_contract(contract_info, abi)
  File "/usr/local/lib/python3.8/site-packages/skale/skale_base.py", line 96, in init_upgradeable_contract
    address = self.get_contract_address(contract_info.contract_name)
  File "/usr/local/lib/python3.8/site-packages/skale/skale_base.py", line 113, in get_contract_address
    return self.contract_manager.get_contract_address(name)
  File "/usr/local/lib/python3.8/site-packages/skale/contracts/contract_manager.py", line 30, in get_contract_address
    return self.contract.functions.contracts(contract_hash).call()
  File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 970, in call
    return call_contract_function(
  File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 1554, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?
```
This seems as some connectivity issue - I had opened completely all firewalls that would be restricting access to the VM both inbound / outbound but the issue remains. Apart from this I think I had been following the instructions from https://docs.skale.network/develop/full-sync-node - with your suggestions of versions to use...

My env file now is:
```
# env
CONTAINER_CONFIGS_STREAM="2.1.15-sync-2.0"
ENDPOINT="https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix"
MANAGER_CONTRACTS_ABI_URL="https://raw.githubusercontent.com/skalenetwork/skale-network/master/releases/mainnet/skale-manager/1.9.0/skale-manager-1.9.0-mainnet-abi.json"
IMA_CONTRACTS_ABI_URL="https://raw.githubusercontent.com/skalenetwork/skale-network/master/releases/mainnet/IMA/1.3.0/mainnet/abi.json"
DISK_MOUNTPOINT=/dev/sdb
DOCKER_LVMPY_STREAM="1.0.2-stable.0"
ENV_TYPE="testnet"
SCHAIN_NAME="staging-fast-active-bellatrix"
ENFORCE_BTRFS="True"
```
I can see these containers are now running:
```
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS                      PORTS     NAMES
22ebb5649fa6   nginx:1.20.2                                "/docker-entrypoint.…"   34 minutes ago   Up 34 minutes                         skale_nginx
9e99bb0db0a9   skalenetwork/admin:2.11.0-sync-node-2.0.0   "python3 sync_node.py"   34 minutes ago   Up 34 minutes (unhealthy)             skale_sync_admin
ac6664d9987c   kubernetes/pause                            "/pause"                 34 minutes ago   Up 34 minutes                         config_base_1
```
Do you have any further hints for me?

**Comment by badrogger** [comment]
@junkett ENDPOINT - ETH endpoint which is Goerli for staging.
You can use infura in this case.
