### ISSUE TITLE
`skale health sgx` broke after adding ZMQ check to watchdog

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/node-cli#792]
Watchdog response to sgx health call has been changed, so `skale health sgx` command logic shoud be changed to match watchdog response

Node-cli: `2.5.0-beta.0`

Old response:
`{"data": {"status": 0, "status_name": "CONNECTED", "sgx_wallet_version": "1.9.0"}, "error": null}`

New response:
`{"data": {"status_zmq": true, "status_https": true, "sgx_wallet_version": "1.9.0"}, "error": null}`

Error log:
```
root@Regression-8:~# skale health sgx
Traceback (most recent call last):
  File "node_cli/main.py", line 122, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "node_cli/cli/health.py", line 59, in sgx
  File "node_cli/core/health.py", line 75, in get_sgx_info
KeyError: 'status_name'
Command failed with following errors:
--------------------------------------------------
'status_name'
--------------------------------------------------
You can find more info in /root/.skale/.skale-cli-log/debug-node-cli.log
```

Related issue: https://github.com/skalenetwork/skale-admin/issues/1014

**Comment by OleksanderSalamatov** [comment]
Verified

skale-admin: `2.8.0-beta.2`
node-cli: `2.5.0-beta.3`

Logs:
```
root@Regression-5:~# skale health sgx
┌───────────────────┬──────────────────────────────────────────────────────────────────────┐
│ SGX info          │                                                                      │
├───────────────────┼──────────────────────────────────────────────────────────────────────┤
│ Server URL        │ https://140.82.27.1:1026                                             │
│ SGXWallet Version │ 1.9.0                                                                │
│ Node SGX keyname  │ NEK:fb82dd8f59f4064fabb84fee5dbe79745d7072c2e4918f6c02ffbeac961c6719 │
│ Status HTTPS      │ True                                                                 │
│ Status ZMQ        │ False                                                                │
└───────────────────┴──────────────────────────────────────────────────────────────────────┘
```
